### ISSUE TITLE
Problem przy klonowaniu repo na macu/windowsie

### ISSUE THREAD

**Issue by Traf27** [iceener/brain#2]
Robiąc git clone, repo sypie takimi błędami:

**mac**
```terminal
error: unable to create file 🏆 Fundamenty/🧭 Kierunek.md: Illegal byte sequence
fatal: cannot create directory at '🦾 Optymalizacja': Illegal byte sequence
warning: Clone succeeded, but checkout failed.
```
**windows**
```terminal
error: invalid path '✨ Co to za miejsce?.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
```
W jaki sposób udaje Ci się używać tego znaku w nazwach pliku/katalogu na macu?
Może by tak zmienić powyższe nazwy na kompatybilne z sys plików? 

Skąd zduplikowane katalogi ? to jakiś szczegół związany z samym Obsidianem?

BTW bardzo dziękuje za dzielenie się tym czym się dzielisz :)

**Comment by iceener** [comment]
Tak, faktycznie jest problem z tym repo. Problemem są emoji w nazwach
plików.
Prawdopodobnie będę to jakoś migrował [image: 🙂]

Tak czy inaczej dziękuję za wiadomość [image: 😁]

Dobrego dnia,
Adam

Serdecznie pozdrawiam,
Adam Gospodarczyk
